name: Daily Buienradar Rain Plot

on:
  schedule:
    - cron: "30 11 * * *" # runs every day at 11:30 UTC
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python buienradar_plot.py

      - name: Upload PNG to OneDrive
        uses: dawidd6/action-upload-to-onedrive@v3
        with:
          source: "buienradar_barplot.png"
          destination: "/buienradar_barplot.png"
          client-id: ${{ secrets.ONEDRIVE_CLIENT_ID }}
          client-secret: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.ONEDRIVE_REFRESH_TOKEN }}
